# This file was generated by GoReleaser. DO NOT EDIT.
cask "agnostic-ai" do
  version "0.50.0"

  on_macos do
    on_arm do
      sha256 "1cc20b2fd77c1febda3fb2952d8858c2304b19ed031b3eb6302cdbf90305f796"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b9da08bfac5c5bac02ec8810569a4d4880b116982f93df1189dbf9df845a066c"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8cd0b4e9aacbbeb1ccc6b4bf27fd486f2da3f3dced3ed6fed6f9d1d6e217b783"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "50c9ed98477f46b65237e1aa74c9474fb29cd8688cdb871b560ab2e17d229a8d"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_linux_amd64.tar.gz"
    end
  end

  name "agnostic-ai"
  desc "Sync agent prompts, skills, rules, and hooks across AI coding tools"
  homepage "https://github.com/Chemaclass/agnostic-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agnostic-ai"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agnostic-ai"]
    end
  end

  # No zap stanza required
end
