# This file was generated by GoReleaser. DO NOT EDIT.
cask "agnostic-ai" do
  version "0.23.0"

  on_macos do
    on_intel do
      sha256 "29bd7205ac40989b7606e4caa3177551cb685417b12c00b82ec035e71114b98b"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1b862c96608147fa98f3ee7de2a9e2c96d8c367306fba2859d59f746af6af0d1"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "afbab121a76e10bb776e489fba9ff8958af739225862675d70fdfd9a7e9914f3"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d21e3cb0616bfc93ede5dd5f6fa46bf811abd973abcbc3a6aa75600e9b0b58f"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_linux_arm64.tar.gz"
    end
  end

  name "agnostic-ai"
  desc "Sync agent prompts, skills, rules, and hooks across AI coding tools"
  homepage "https://github.com/Chemaclass/agnostic-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agnostic-ai"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agnostic-ai"]
    end
  end

  # No zap stanza required

end
