# This file was generated by GoReleaser. DO NOT EDIT.
cask "agnostic-ai" do
  version "0.80.0"

  on_macos do
    on_arm do
      sha256 "54d2c66122f695bd606160f224bf3ba05f952dfcc0ca24f37c1a5e5e4255070d"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fb97b2c73003aeb9feaedbf06ca40ec408f3f68cff3e25f787f16386d54a24e6"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2116efb36091a6f13d2719ca19586ae52c22e500ac0d1c523d67485ac5f79110"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "272de481302b0d1079616f5c039ca2f389cb826a701beca2ae6979bbb6ae3a9f"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_linux_amd64.tar.gz"
    end
  end

  name "agnostic-ai"
  desc "Sync agent prompts, skills, rules, and hooks across AI coding tools"
  homepage "https://github.com/Chemaclass/agnostic-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agnostic-ai"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/agnostic-ai"]
    end
  end

  # No zap stanza required
end
