# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgnosticAi < Formula
  desc "Sync agent prompts, skills, rules, and hooks across AI coding tools"
  homepage "https://github.com/Chemaclass/agnostic-ai"
  version "0.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v0.15.0/agnostic-ai_darwin_amd64.tar.gz"
      sha256 "3fb6e04323474c089e93c9c350a36735bd9e3fbd021f569285eeadbd383123f7"

      define_method(:install) do
        bin.install "agnostic-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v0.15.0/agnostic-ai_darwin_arm64.tar.gz"
      sha256 "ee2a12185b4fb00cb3a4e5b255870804bfd23a135fd67a371e9b998d2afc86f5"

      define_method(:install) do
        bin.install "agnostic-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v0.15.0/agnostic-ai_linux_amd64.tar.gz"
      sha256 "1f21256498c31112d6dc3264f4e8ffe587f0b3c900e202a5057a8353fb8ee6a7"
      define_method(:install) do
        bin.install "agnostic-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v0.15.0/agnostic-ai_linux_arm64.tar.gz"
      sha256 "dfcd1d1c4d0741c00d38ad610a596111e15df890f1784c800afa66454a249e08"
      define_method(:install) do
        bin.install "agnostic-ai"
      end
    end
  end

  test do
    system "#{bin}/agnostic-ai", "--help"
  end
end
