#!/usr/bin/env bash
# Regenerate Casks/agnostic-ai.rb for the latest agnostic-ai release.
#
# This exists because pushing the cask from the agnostic-ai release workflow
# needs a credential that can write to *this* repository, and GitHub offers no
# API to mint one: a GitHub App and a personal access token are both browser
# flows. So the release stopped being the thing that pushes. This repository
# updates its own cask with the GITHUB_TOKEN every workflow already has, which
# never expires and needs no secret.
#
# It is also self-healing. A release that happens while this workflow is
# broken is picked up by the next scheduled run, instead of leaving brew on an
# old version until someone notices.
#
# Output matches what GoReleaser writes byte for byte, so if the token route
# is ever configured the two agree and neither produces a diff.
set -euo pipefail

REPO="${REPO:-Chemaclass/agnostic-ai}"
CASK="${CASK:-Casks/agnostic-ai.rb}"

tag="${1:-}"
if [ -z "$tag" ]; then
  # The releases/latest redirect, not the API: it needs no token and is not
  # subject to the 60-requests-an-hour unauthenticated cap.
  tag=$(curl -fsSLI -o /dev/null -w '%{url_effective}' \
    "https://github.com/${REPO}/releases/latest" | sed 's#.*/tag/##')
fi
[ -n "$tag" ] || { echo "could not resolve the latest tag" >&2; exit 1; }
version="${tag#v}"

current=$(grep -m1 -oE 'version "[^"]+"' "$CASK" 2>/dev/null | cut -d'"' -f2 || true)
if [ "$current" = "$version" ]; then
  echo "cask is already $version"
  exit 0
fi

sums=$(curl -fsSL "https://github.com/${REPO}/releases/download/${tag}/checksums.txt")

sha_for() {
  local name="$1" sum
  sum=$(awk -v n="$name" '$2 == n { print $1 }' <<<"$sums")
  [ -n "$sum" ] || { echo "no checksum for $name in ${tag}" >&2; exit 1; }
  printf '%s' "$sum"
}

darwin_arm=$(sha_for agnostic-ai_darwin_arm64.tar.gz)
darwin_intel=$(sha_for agnostic-ai_darwin_amd64.tar.gz)
linux_arm=$(sha_for agnostic-ai_linux_arm64.tar.gz)
linux_intel=$(sha_for agnostic-ai_linux_amd64.tar.gz)

cat > "$CASK" <<CASKFILE
# This file was generated by GoReleaser. DO NOT EDIT.
cask "agnostic-ai" do
  version "${version}"

  on_macos do
    on_arm do
      sha256 "${darwin_arm}"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "${darwin_intel}"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "${linux_arm}"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "${linux_intel}"
      url "https://github.com/Chemaclass/agnostic-ai/releases/download/v#{version}/agnostic-ai_linux_amd64.tar.gz"
    end
  end

  name "agnostic-ai"
  desc "Sync agent prompts, skills, rules, and hooks across AI coding tools"
  homepage "https://github.com/Chemaclass/agnostic-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agnostic-ai"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/agnostic-ai"]
    end
  end

  # No zap stanza required
end
CASKFILE

echo "cask updated ${current:-<absent>} -> ${version}"
